set(CONFIG_FREERTOS 1)
set(CONFIG_SHELL 1)

set(CONFIG_CHERRYUSB 1)
set(CONFIG_CHERRYUSB_OSAL "freertos")

if("${CHIP}" STREQUAL "qcc74x_undef")
    # usb_v1, only support device mode
    set(CONFIG_CHERRYUSB_DEVICE 1)
    set(CONFIG_CHERRYUSB_DEVICE_CDC_ACM 1)
    set(CONFIG_CHERRYUSB_DEVICE_CDC_ECM 1)
    set(CONFIG_CHERRYUSB_DEVICE_CDC_RNDIS 1)
    set(CONFIG_CHERRYUSB_DEVICE_HID 1)
    set(CONFIG_CHERRYUSB_DEVICE_MSC 0) # No enough ram

    set(CONFIG_CHERRYUSB_HOST 0)

else()

    # usb device options
    set(CONFIG_CHERRYUSB_DEVICE 1)
    set(CONFIG_CHERRYUSB_DEVICE_CDC_ACM 1)
    set(CONFIG_CHERRYUSB_DEVICE_CDC_ECM 1)
    set(CONFIG_CHERRYUSB_DEVICE_CDC_RNDIS 1)
    set(CONFIG_CHERRYUSB_DEVICE_HID 1)
    set(CONFIG_CHERRYUSB_DEVICE_MSC 1)
    set(CONFIG_CHERRYUSB_DEVICE_AUDIO 1)
    set(CONFIG_CHERRYUSB_DEVICE_VIDEO 1)

    # usb host options
    set(CONFIG_CHERRYUSB_HOST 1)
    set(CONFIG_CHERRYUSB_HOST_CDC_ACM 1)
    set(CONFIG_CHERRYUSB_HOST_HID 1)
    set(CONFIG_CHERRYUSB_HOST_MSC 1)

endif()

if(CONFIG_CHERRYUSB_DEVICE_CDC_ECM OR CONFIG_CHERRYUSB_DEVICE_CDC_RNDIS)
    set(CONFIG_BSP_ETH_PHY 1)
endif()

if(CONFIG_CHERRYUSB_HOST_MSC)
    set(CONFIG_FATFS 1)
    set(CONFIG_FATFS_USBH 1)
endif()
