#!/bin/bash

killall DebugServerConsole.elf
DebugServerConsole &

cd ..
# Get the name of the current folder.
current_folder=$(basename "$PWD")

current_dir=$PWD
riscv64-unknown-elf-gdb $current_dir/build/build_out/${current_folder}_qcc743.elf -x ./gdb/gdbinit

